using System.Collections.Generic;

public static class TriviaQuestionBank
{
    public static List<TriviaQuestion> GetAllQuestions()
    {
        return new List<TriviaQuestion>
        {
            // ===== MICHAEL JACKSON =====
            new TriviaQuestion { question = "Which artist is known as the King of Pop?", answers = new string[] { "Michael Jackson" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Michael Jackson's signature dance move?", answers = new string[] { "The Moonwalk" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was the name of Michael Jackson's famous estate?", answers = new string[] { "Neverland Ranch" }, correctIndex = 0 },
            new TriviaQuestion { question = "Which Michael Jackson album is the best-selling album of all time?", answers = new string[] { "Thriller" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year did Michael Jackson release Thriller?", answers = new string[] { "1982" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was the name of Michael Jackson's pet chimpanzee?", answers = new string[] { "Bubbles" }, correctIndex = 0 },
            new TriviaQuestion { question = "How many siblings did Michael Jackson have in the Jackson 5?", answers = new string[] { "Four (Jackie, Tito, Jermaine, Marlon)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music video featured Michael Jackson turning into a werewolf?", answers = new string[] { "Thriller" }, correctIndex = 0 },
            new TriviaQuestion { question = "What song did Michael Jackson perform at the 1993 Super Bowl?", answers = new string[] { "Jam, Billie Jean, Black or White" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Michael Jackson song starts with 'She was more like a beauty queen'?", answers = new string[] { "Billie Jean" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Michael Jackson's first solo number one hit?", answers = new string[] { "Don't Stop 'Til You Get Enough" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was the name of Michael Jackson's final concert series?", answers = new string[] { "This Is It" }, correctIndex = 0 },

            // ===== BEYONCE =====
            new TriviaQuestion { question = "What girl group was Beyonce a member of before going solo?", answers = new string[] { "Destiny's Child" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Beyonce's 2016 visual album?", answers = new string[] { "Lemonade" }, correctIndex = 0 },
            new TriviaQuestion { question = "Who is Beyonce married to?", answers = new string[] { "Jay-Z" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Beyonce song features the lyric 'All the single ladies'?", answers = new string[] { "Single Ladies (Put a Ring on It)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Beyonce's first solo number one hit?", answers = new string[] { "Crazy in Love" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Beyonce's eldest daughter?", answers = new string[] { "Blue Ivy" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was the name of Beyonce's 2022 album?", answers = new string[] { "Renaissance" }, correctIndex = 0 },
            new TriviaQuestion { question = "What artist holds the record for most Grammy wins of all time?", answers = new string[] { "Beyonce" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Beyonce song became an anthem for female empowerment with 'Who run the world'?", answers = new string[] { "Girls" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was the name of Beyonce's surprise self-titled album in 2013?", answers = new string[] { "Beyonce" }, correctIndex = 0 },
            new TriviaQuestion { question = "What NFL event did Beyonce perform at during halftime in 2016?", answers = new string[] { "Super Bowl 50" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Beyonce song features Jay-Z and starts with 'Uh oh uh oh'?", answers = new string[] { "Crazy in Love" }, correctIndex = 0 },

            // ===== DRAKE =====
            new TriviaQuestion { question = "What is Drake's real full name?", answers = new string[] { "Aubrey Drake Graham" }, correctIndex = 0 },
            new TriviaQuestion { question = "Which TV show did Drake star in before his music career?", answers = new string[] { "Degrassi" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Drake from?", answers = new string[] { "Canada" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Drake's record label?", answers = new string[] { "OVO Sound" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does OVO stand for in Drake's brand?", answers = new string[] { "October's Very Own" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Drake album features the song 'Hotline Bling'?", answers = new string[] { "Views" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is Drake most associated with?", answers = new string[] { "Toronto" }, correctIndex = 0 },
            new TriviaQuestion { question = "What character did Drake play on Degrassi?", answers = new string[] { "Jimmy Brooks" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Drake song went viral with a dance challenge on TikTok in 2020?", answers = new string[] { "Toosie Slide" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Drake's debut studio album called?", answers = new string[] { "Thank Me Later" }, correctIndex = 0 },

            // ===== RIHANNA =====
            new TriviaQuestion { question = "Which Caribbean island is Rihanna from?", answers = new string[] { "Barbados" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Rihanna's full real name?", answers = new string[] { "Robyn Rihanna Fenty" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Rihanna's cosmetics brand?", answers = new string[] { "Fenty Beauty" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Rihanna hit features the lyric 'shine bright like a diamond'?", answers = new string[] { "Diamonds" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Rihanna's lingerie brand called?", answers = new string[] { "Savage X Fenty" }, correctIndex = 0 },
            new TriviaQuestion { question = "What major sporting event did Rihanna perform at in 2023?", answers = new string[] { "Super Bowl halftime show" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Rihanna's debut single?", answers = new string[] { "Pon de Replay" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Rihanna song features the lyric 'under my umbrella ella ella'?", answers = new string[] { "Umbrella" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year did Rihanna release the album Anti?", answers = new string[] { "2016" }, correctIndex = 0 },

            // ===== TAYLOR SWIFT =====
            new TriviaQuestion { question = "What genre did Taylor Swift start her career in?", answers = new string[] { "Country" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Taylor Swift's record-breaking 2023 concert tour?", answers = new string[] { "The Eras Tour" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Taylor Swift album was re-recorded first?", answers = new string[] { "Fearless (Taylor's Version)" }, correctIndex = 0 },
            new TriviaQuestion { question = "Which Taylor Swift song has the lyric 'players gonna play'?", answers = new string[] { "Shake It Off" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Taylor Swift album features the songs 'Cardigan' and 'Exile'?", answers = new string[] { "Folklore" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Taylor Swift's fan base?", answers = new string[] { "Swifties" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Taylor Swift album has a snake theme?", answers = new string[] { "Reputation" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year did Taylor Swift release her debut album?", answers = new string[] { "2006" }, correctIndex = 0 },
            new TriviaQuestion { question = "Why did Taylor Swift re-record her albums?", answers = new string[] { "To own her masters after Scooter Braun acquired them" }, correctIndex = 0 },

            // ===== LADY GAGA =====
            new TriviaQuestion { question = "What is Lady Gaga's real name?", answers = new string[] { "Stefani Joanne Angelina Germanotta" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Lady Gaga's debut single?", answers = new string[] { "Just Dance" }, correctIndex = 0 },
            new TriviaQuestion { question = "What movie did Lady Gaga star in with Bradley Cooper?", answers = new string[] { "A Star Is Born" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous outfit did Lady Gaga wear to the 2010 MTV VMAs?", answers = new string[] { "The meat dress" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Lady Gaga's fan base called?", answers = new string[] { "Little Monsters" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Oscar-winning song did Lady Gaga perform from A Star Is Born?", answers = new string[] { "Shallow" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Lady Gaga song features the lyric 'I'm on the edge of glory'?", answers = new string[] { "The Edge of Glory" }, correctIndex = 0 },

            // ===== KANYE WEST / YE =====
            new TriviaQuestion { question = "What name did Kanye West legally change his name to?", answers = new string[] { "Ye" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Kanye West's debut album?", answers = new string[] { "The College Dropout" }, correctIndex = 0 },
            new TriviaQuestion { question = "What fashion brand did Kanye create with Adidas?", answers = new string[] { "Yeezy" }, correctIndex = 0 },
            new TriviaQuestion { question = "Which award show did Kanye famously interrupt Taylor Swift at?", answers = new string[] { "2009 MTV VMAs" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Kanye West album is named after his late mother?", answers = new string[] { "Donda" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is Kanye West originally from?", answers = new string[] { "Chicago" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Kanye song features the lyric 'I guess we'll never know'?", answers = new string[] { "Runaway" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Kanye West's second album called?", answers = new string[] { "Late Registration" }, correctIndex = 0 },

            // ===== ADELE =====
            new TriviaQuestion { question = "What country is Adele from?", answers = new string[] { "England" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Adele song opens with 'Hello it's me'?", answers = new string[] { "Hello" }, correctIndex = 0 },
            new TriviaQuestion { question = "Adele's albums are named after what?", answers = new string[] { "Her age when she wrote them" }, correctIndex = 0 },
            new TriviaQuestion { question = "Which James Bond movie did Adele sing the theme for?", answers = new string[] { "Skyfall" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Adele song features the lyric 'rolling in the deep'?", answers = new string[] { "Rolling in the Deep" }, correctIndex = 0 },
            new TriviaQuestion { question = "What number is Adele's most recent album titled?", answers = new string[] { "30" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city did Adele have a famous residency in?", answers = new string[] { "Las Vegas" }, correctIndex = 0 },

            // ===== WHITNEY HOUSTON =====
            new TriviaQuestion { question = "What Whitney Houston song is famously performed at every karaoke night?", answers = new string[] { "I Will Always Love You" }, correctIndex = 0 },
            new TriviaQuestion { question = "What movie did Whitney Houston star in with Kevin Costner?", answers = new string[] { "The Bodyguard" }, correctIndex = 0 },
            new TriviaQuestion { question = "Who originally wrote 'I Will Always Love You' before Whitney Houston?", answers = new string[] { "Dolly Parton" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Whitney Houston's first number one hit?", answers = new string[] { "Saving All My Love for You" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Whitney Houston's daughter's name?", answers = new string[] { "Bobbi Kristina Brown" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Whitney Houston song features the lyric 'I believe the children are our future'?", answers = new string[] { "Greatest Love of All" }, correctIndex = 0 },

            // ===== BRUNO MARS =====
            new TriviaQuestion { question = "What is Bruno Mars' real name?", answers = new string[] { "Peter Gene Hernandez" }, correctIndex = 0 },
            new TriviaQuestion { question = "What duo did Bruno Mars form with Anderson .Paak?", answers = new string[] { "Silk Sonic" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Bruno Mars song has the lyric 'catch a grenade for ya'?", answers = new string[] { "Grenade" }, correctIndex = 0 },
            new TriviaQuestion { question = "What state is Bruno Mars from?", answers = new string[] { "Hawaii" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Bruno Mars song starts with 'Today I don't feel like doing anything'?", answers = new string[] { "The Lazy Song" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Silk Sonic single won Record of the Year at the Grammys?", answers = new string[] { "Leave the Door Open" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Super Bowl halftime show did Bruno Mars perform at twice?", answers = new string[] { "Super Bowl XLVIII (2014) and Super Bowl 50 (2016)" }, correctIndex = 0 },

            // ===== ARIANA GRANDE =====
            new TriviaQuestion { question = "What Nickelodeon show did Ariana Grande star in?", answers = new string[] { "Victorious" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Ariana Grande's signature hairstyle?", answers = new string[] { "High ponytail" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ariana Grande song repeats 'thank u next'?", answers = new string[] { "Thank U, Next" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ariana Grande album features '7 Rings'?", answers = new string[] { "Thank U, Next" }, correctIndex = 0 },
            new TriviaQuestion { question = "What role did Ariana Grande play in the movie musical Wicked?", answers = new string[] { "Glinda" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Ariana Grande's perfume line?", answers = new string[] { "Cloud" }, correctIndex = 0 },

            // ===== JUSTIN BIEBER =====
            new TriviaQuestion { question = "What platform was Justin Bieber discovered on?", answers = new string[] { "YouTube" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Justin Bieber's breakout single?", answers = new string[] { "Baby" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Justin Bieber from?", answers = new string[] { "Canada" }, correctIndex = 0 },
            new TriviaQuestion { question = "Who discovered Justin Bieber?", answers = new string[] { "Scooter Braun" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Justin Bieber's wife's name?", answers = new string[] { "Hailey Bieber" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Justin Bieber song went viral with the lyric 'Is it too late now to say sorry'?", answers = new string[] { "Sorry" }, correctIndex = 0 },

            // ===== TEMS =====
            new TriviaQuestion { question = "What country is Tems from?", answers = new string[] { "Nigeria" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Tems' real name?", answers = new string[] { "Temilade Openiyi" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Wizkid song features Tems and became a global hit?", answers = new string[] { "Essence" }, correctIndex = 0 },
            new TriviaQuestion { question = "What award did Tems win at the 2023 Grammys?", answers = new string[] { "Best Melodic Rap Performance (for Wait for U)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Future song features Tems and Drake?", answers = new string[] { "Wait for U" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Tems' debut EP called?", answers = new string[] { "For Broken Ears" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Beyonce song from Renaissance features a Tems sample?", answers = new string[] { "Move" }, correctIndex = 0 },

            // ===== FREDDIE MERCURY =====
            new TriviaQuestion { question = "What band was Freddie Mercury the lead singer of?", answers = new string[] { "Queen" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country was Freddie Mercury born in?", answers = new string[] { "Zanzibar (Tanzania)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Freddie Mercury's real birth name?", answers = new string[] { "Farrokh Bulsara" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Queen song is famous for its operatic section?", answers = new string[] { "Bohemian Rhapsody" }, correctIndex = 0 },
            new TriviaQuestion { question = "What 2018 movie was a biopic about Freddie Mercury?", answers = new string[] { "Bohemian Rhapsody" }, correctIndex = 0 },
            new TriviaQuestion { question = "What stadium did Queen perform their legendary 1985 Live Aid set at?", answers = new string[] { "Wembley Stadium" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Queen song is played at almost every sporting event with the lyric 'We will rock you'?", answers = new string[] { "We Will Rock You" }, correctIndex = 0 },

            // ===== POP SMOKE =====
            new TriviaQuestion { question = "What city was Pop Smoke from?", answers = new string[] { "Brooklyn, New York" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Pop Smoke's real name?", answers = new string[] { "Bashar Barakah Jackson" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Pop Smoke song became a viral TikTok hit?", answers = new string[] { "Dior" }, correctIndex = 0 },
            new TriviaQuestion { question = "What subgenre of hip hop is Pop Smoke known for pioneering?", answers = new string[] { "Brooklyn drill" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Pop Smoke's posthumous album called?", answers = new string[] { "Shoot for the Stars Aim for the Moon" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year did Pop Smoke pass away?", answers = new string[] { "2020" }, correctIndex = 0 },

            // ===== TRAVIS SCOTT =====
            new TriviaQuestion { question = "What is Travis Scott's real name?", answers = new string[] { "Jacques Bermon Webster II" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Travis Scott's music festival?", answers = new string[] { "Astroworld" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is Travis Scott from?", answers = new string[] { "Houston, Texas" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Travis Scott album shares a name with a defunct theme park?", answers = new string[] { "Astroworld" }, correctIndex = 0 },
            new TriviaQuestion { question = "What fast food chain did Travis Scott have a famous meal collaboration with?", answers = new string[] { "McDonald's" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Travis Scott song features the lyric 'it's lit'?", answers = new string[] { "Sicko Mode" }, correctIndex = 0 },
            new TriviaQuestion { question = "Who is the mother of Travis Scott's children?", answers = new string[] { "Kylie Jenner" }, correctIndex = 0 },

            // ===== CENTRAL CEE =====
            new TriviaQuestion { question = "What country is Central Cee from?", answers = new string[] { "England (London)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Central Cee's real name?", answers = new string[] { "Oakley Neil H T Caesar-Su" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre is Central Cee known for?", answers = new string[] { "UK rap / drill" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Central Cee song went viral with the lyric 'I know you want Chanel'?", answers = new string[] { "Doja" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Dave song features Central Cee?", answers = new string[] { "Sprinter" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Central Cee's breakout mixtape called?", answers = new string[] { "Wild West" }, correctIndex = 0 },

            // ===== BURNA BOY =====
            new TriviaQuestion { question = "What country is Burna Boy from?", answers = new string[] { "Nigeria" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Burna Boy's real name?", answers = new string[] { "Damini Ebunoluwa Ogulu" }, correctIndex = 0 },
            new TriviaQuestion { question = "What title does Burna Boy go by?", answers = new string[] { "The African Giant" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Burna Boy album won the Grammy for Best Global Music Album?", answers = new string[] { "Twice as Tall" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Burna Boy's hit song that features the lyric 'anybody wey see shayo'?", answers = new string[] { "Last Last" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous Toni Braxton song did Burna Boy sample in Last Last?", answers = new string[] { "He Wasn't Man Enough" }, correctIndex = 0 },
            new TriviaQuestion { question = "What stadium in London did Burna Boy sell out in 2023?", answers = new string[] { "London Stadium" }, correctIndex = 0 },

            // ===== EMINEM =====
            new TriviaQuestion { question = "What is Eminem's real name?", answers = new string[] { "Marshall Bruce Mathers III" }, correctIndex = 0 },
            new TriviaQuestion { question = "What movie did Eminem star in about a Detroit rapper?", answers = new string[] { "8 Mile" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Eminem's alter ego?", answers = new string[] { "Slim Shady" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is Eminem from?", answers = new string[] { "Detroit, Michigan" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Eminem song from 8 Mile won an Oscar?", answers = new string[] { "Lose Yourself" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Eminem's debut major label album?", answers = new string[] { "The Slim Shady LP" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Eminem song is addressed to an obsessive fan?", answers = new string[] { "Stan" }, correctIndex = 0 },
            new TriviaQuestion { question = "What word now in the dictionary originated from an Eminem song?", answers = new string[] { "Stan (meaning obsessive fan)" }, correctIndex = 0 },

            // ===== JAY-Z =====
            new TriviaQuestion { question = "What is Jay-Z's real name?", answers = new string[] { "Shawn Corey Carter" }, correctIndex = 0 },
            new TriviaQuestion { question = "What record label did Jay-Z co-found?", answers = new string[] { "Roc-A-Fella Records" }, correctIndex = 0 },
            new TriviaQuestion { question = "What streaming service does Jay-Z own?", answers = new string[] { "Tidal" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Jay-Z's debut album?", answers = new string[] { "Reasonable Doubt" }, correctIndex = 0 },
            new TriviaQuestion { question = "What borough of New York is Jay-Z from?", answers = new string[] { "Brooklyn" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Jay-Z album features the song 'Empire State of Mind'?", answers = new string[] { "The Blueprint 3" }, correctIndex = 0 },
            new TriviaQuestion { question = "How many number one albums does Jay-Z have?", answers = new string[] { "14" }, correctIndex = 0 },

            // ===== DAVE =====
            new TriviaQuestion { question = "What country is rapper Dave from?", answers = new string[] { "England (London)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Dave's full name?", answers = new string[] { "David Orobosa Omoregie" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Dave album won the Mercury Prize?", answers = new string[] { "Psychodrama" }, correctIndex = 0 },
            new TriviaQuestion { question = "What viral Dave and Central Cee collaboration topped the UK charts?", answers = new string[] { "Sprinter" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Dave's second album called?", answers = new string[] { "We're All Alone in This Together" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nigerian heritage does Dave have?", answers = new string[] { "He is of Nigerian descent" }, correctIndex = 0 },

            // ===== KENDRICK LAMAR =====
            new TriviaQuestion { question = "What city is Kendrick Lamar from?", answers = new string[] { "Compton, California" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Kendrick Lamar album won the Pulitzer Prize for Music?", answers = new string[] { "DAMN." }, correctIndex = 0 },
            new TriviaQuestion { question = "What Kendrick Lamar song became an anthem with 'we gon' be alright'?", answers = new string[] { "Alright" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Kendrick Lamar's major label debut album?", answers = new string[] { "good kid, m.A.A.d city" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Kendrick Lamar album features songs about systemic racism and Black culture?", answers = new string[] { "To Pimp a Butterfly" }, correctIndex = 0 },
            new TriviaQuestion { question = "What record label is Kendrick Lamar signed to?", answers = new string[] { "pgLang / Interscope" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Kendrick Lamar song went viral in 2024 during a rap beef?", answers = new string[] { "Not Like Us" }, correctIndex = 0 },

            // ===== CHRIS BROWN =====
            new TriviaQuestion { question = "What was Chris Brown's debut single?", answers = new string[] { "Run It!" }, correctIndex = 0 },
            new TriviaQuestion { question = "How old was Chris Brown when he released his first album?", answers = new string[] { "16" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Chris Brown song features the lyric 'these hoes ain't loyal'?", answers = new string[] { "Loyal" }, correctIndex = 0 },
            new TriviaQuestion { question = "What state is Chris Brown from?", answers = new string[] { "Virginia" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Chris Brown known for besides singing?", answers = new string[] { "Dancing" }, correctIndex = 0 },

            // ===== TYLA =====
            new TriviaQuestion { question = "What country is Tyla from?", answers = new string[] { "South Africa" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Tyla song went massively viral on TikTok?", answers = new string[] { "Water" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre is Tyla associated with?", answers = new string[] { "Amapiano" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Grammy did Tyla win in 2024?", answers = new string[] { "Best African Music Performance" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Tyla's full name?", answers = new string[] { "Tyla Laura Seethal" }, correctIndex = 0 },

            // ===== USHER =====
            new TriviaQuestion { question = "What was Usher's biggest hit from 2004?", answers = new string[] { "Yeah!" }, correctIndex = 0 },
            new TriviaQuestion { question = "What major event did Usher perform the halftime show at in 2024?", answers = new string[] { "Super Bowl LVIII" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city did Usher have a famous Las Vegas residency in?", answers = new string[] { "Las Vegas" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Usher's full name?", answers = new string[] { "Usher Raymond IV" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Usher album features 'Burn' and 'Confessions Part II'?", answers = new string[] { "Confessions" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous artist did Usher help discover?", answers = new string[] { "Justin Bieber" }, correctIndex = 0 },

            // ===== ICE SPICE =====
            new TriviaQuestion { question = "What city is Ice Spice from?", answers = new string[] { "The Bronx, New York" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ice Spice song went viral in 2023?", answers = new string[] { "Munch (Feelin' U)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Ice Spice's real name?", answers = new string[] { "Isis Gaston" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Taylor Swift song features Ice Spice?", answers = new string[] { "Karma" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Ice Spice's fan base called?", answers = new string[] { "Munchkins" }, correctIndex = 0 },

            // ===== SZA =====
            new TriviaQuestion { question = "What is SZA's real name?", answers = new string[] { "Solana Imani Rowe" }, correctIndex = 0 },
            new TriviaQuestion { question = "What SZA album features 'Kill Bill' and 'Shirt'?", answers = new string[] { "SOS" }, correctIndex = 0 },
            new TriviaQuestion { question = "What record label is SZA signed to?", answers = new string[] { "Top Dawg Entertainment (TDE)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was SZA's debut studio album?", answers = new string[] { "Ctrl" }, correctIndex = 0 },
            new TriviaQuestion { question = "What SZA song references killing an ex's new girlfriend?", answers = new string[] { "Kill Bill" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does SZA stand for?", answers = new string[] { "Sovereign Zig-zag Angles (or Ruler)" }, correctIndex = 0 },

            // ===== AYRA STARR =====
            new TriviaQuestion { question = "What country is Ayra Starr from?", answers = new string[] { "Nigeria" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ayra Starr song became a massive global hit?", answers = new string[] { "Rush" }, correctIndex = 0 },
            new TriviaQuestion { question = "What record label is Ayra Starr signed to?", answers = new string[] { "Mavin Records" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Ayra Starr's real name?", answers = new string[] { "Oyinkansola Sarah Aderibigbe" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Ayra Starr's debut album called?", answers = new string[] { "19 & Dangerous" }, correctIndex = 0 },

            // ===== ELVIS PRESLEY =====
            new TriviaQuestion { question = "Who is known as the King of Rock and Roll?", answers = new string[] { "Elvis Presley" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Elvis Presley's famous home in Memphis called?", answers = new string[] { "Graceland" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Elvis Presley's nickname?", answers = new string[] { "The King" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Elvis song features the lyric 'you ain't nothing but a hound dog'?", answers = new string[] { "Hound Dog" }, correctIndex = 0 },

            // ===== MADONNA =====
            new TriviaQuestion { question = "Who is known as the Queen of Pop?", answers = new string[] { "Madonna" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Madonna's full name?", answers = new string[] { "Madonna Louise Ciccone" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Madonna song features the lyric 'living in a material world'?", answers = new string[] { "Material Girl" }, correctIndex = 0 },
            new TriviaQuestion { question = "What decade did Madonna rise to fame?", answers = new string[] { "The 1980s" }, correctIndex = 0 },

            // ===== THE WEEKND =====
            new TriviaQuestion { question = "What is The Weeknd's real name?", answers = new string[] { "Abel Tesfaye" }, correctIndex = 0 },
            new TriviaQuestion { question = "What The Weeknd song was a massive hit during 2020?", answers = new string[] { "Blinding Lights" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is The Weeknd originally from?", answers = new string[] { "Canada (Ethiopian heritage)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What The Weeknd album features 'Starboy' and 'I Feel It Coming'?", answers = new string[] { "Starboy" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was The Weeknd's breakout mixtape?", answers = new string[] { "House of Balloons" }, correctIndex = 0 },
            new TriviaQuestion { question = "What major event did The Weeknd perform the halftime show at in 2021?", answers = new string[] { "Super Bowl LV" }, correctIndex = 0 },

            // ===== BILLIE EILISH =====
            new TriviaQuestion { question = "What Billie Eilish song was the theme for a James Bond movie?", answers = new string[] { "No Time to Die" }, correctIndex = 0 },
            new TriviaQuestion { question = "Who produces most of Billie Eilish's music?", answers = new string[] { "Finneas (her brother)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Billie Eilish's debut album called?", answers = new string[] { "When We All Fall Asleep Where Do We Go" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Billie Eilish song went viral when she was 14?", answers = new string[] { "Ocean Eyes" }, correctIndex = 0 },
            new TriviaQuestion { question = "What hair color was Billie Eilish famous for before going blonde?", answers = new string[] { "Black and green" }, correctIndex = 0 },
            new TriviaQuestion { question = "How old was Billie Eilish when she won her first Grammy?", answers = new string[] { "18" }, correctIndex = 0 },

            // ===== PRINCE =====
            new TriviaQuestion { question = "What instrument was Prince famously skilled at?", answers = new string[] { "Guitar (and many others)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Prince song and movie are associated with the color purple?", answers = new string[] { "Purple Rain" }, correctIndex = 0 },
            new TriviaQuestion { question = "What symbol did Prince change his name to?", answers = new string[] { "The Love Symbol (unpronounceable)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is Prince from?", answers = new string[] { "Minneapolis, Minnesota" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Prince song features the lyric 'I just want your extra time and your kiss'?", answers = new string[] { "Kiss" }, correctIndex = 0 },

            // ===== NICKI MINAJ =====
            new TriviaQuestion { question = "What is Nicki Minaj's real name?", answers = new string[] { "Onika Tanya Maraj-Petty" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country was Nicki Minaj born in?", answers = new string[] { "Trinidad and Tobago" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Nicki Minaj's fan base called?", answers = new string[] { "Barbz" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Nicki Minaj's debut album?", answers = new string[] { "Pink Friday" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nicki Minaj song features the lyric 'I'm a bad b'?", answers = new string[] { "Anaconda" }, correctIndex = 0 },
            new TriviaQuestion { question = "What alter ego does Nicki Minaj sometimes perform as?", answers = new string[] { "Roman Zolanski" }, correctIndex = 0 },

            // ===== CARDI B =====
            new TriviaQuestion { question = "What is Cardi B's real name?", answers = new string[] { "Belcalis Marlenis Almanzar" }, correctIndex = 0 },
            new TriviaQuestion { question = "What reality TV show did Cardi B appear on?", answers = new string[] { "Love & Hip Hop: New York" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Cardi B's first number one hit?", answers = new string[] { "Bodak Yellow" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Cardi B's debut album?", answers = new string[] { "Invasion of Privacy" }, correctIndex = 0 },
            new TriviaQuestion { question = "Who is Cardi B married to?", answers = new string[] { "Offset" }, correctIndex = 0 },

            // ===== WIZKID =====
            new TriviaQuestion { question = "What is Wizkid's real name?", answers = new string[] { "Ayodeji Ibrahim Balogun" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Wizkid from?", answers = new string[] { "Nigeria" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Wizkid and Tems song became a global hit?", answers = new string[] { "Essence" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Wizkid's album that featured Essence called?", answers = new string[] { "Made in Lagos" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Drake song features Wizkid?", answers = new string[] { "One Dance" }, correctIndex = 0 },

            // ===== SARKODIE =====
            new TriviaQuestion { question = "What country is Sarkodie from?", answers = new string[] { "Ghana" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Sarkodie's real name?", answers = new string[] { "Michael Owusu Addo" }, correctIndex = 0 },
            new TriviaQuestion { question = "What award has Sarkodie won multiple times at the BET Hip Hop Awards?", answers = new string[] { "Best International Flow" }, correctIndex = 0 },
            new TriviaQuestion { question = "What language does Sarkodie primarily rap in?", answers = new string[] { "Twi" }, correctIndex = 0 },

            // ===== GENERAL MUSIC KNOWLEDGE =====
            new TriviaQuestion { question = "What app is most associated with short music clips and dances?", answers = new string[] { "TikTok" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music streaming platform has a green logo?", answers = new string[] { "Spotify" }, correctIndex = 0 },
            new TriviaQuestion { question = "What award show gives out golden gramophone trophies?", answers = new string[] { "The Grammys" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music festival takes place in Coachella Valley California?", answers = new string[] { "Coachella" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does BTS stand for?", answers = new string[] { "Bangtan Sonyeondan (Beyond The Scene)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year was Spotify launched?", answers = new string[] { "2008" }, correctIndex = 0 },
            new TriviaQuestion { question = "What pop group had members named Scary, Sporty, Baby, Ginger and Posh?", answers = new string[] { "Spice Girls" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does DJ stand for?", answers = new string[] { "Disc Jockey" }, correctIndex = 0 },
            new TriviaQuestion { question = "What instrument has 88 keys?", answers = new string[] { "Piano" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the highest female singing voice called?", answers = new string[] { "Soprano" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music genre originated in Jamaica?", answers = new string[] { "Reggae" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is known as the birthplace of hip hop?", answers = new string[] { "New York (The Bronx)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does EP stand for in music?", answers = new string[] { "Extended Play" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country did K-pop originate from?", answers = new string[] { "South Korea" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was the first music video ever played on MTV?", answers = new string[] { "Video Killed the Radio Star by The Buggles" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does LP stand for in music?", answers = new string[] { "Long Play" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the lowest male singing voice called?", answers = new string[] { "Bass" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre of music originated in the Bronx in the 1970s?", answers = new string[] { "Hip hop" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does R&B stand for?", answers = new string[] { "Rhythm and Blues" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of the annual UK music awards ceremony?", answers = new string[] { "The BRIT Awards" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Amapiano music from?", answers = new string[] { "South Africa" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does a music producer do?", answers = new string[] { "Creates beats and oversees the recording process" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a Grammy Award officially called?", answers = new string[] { "Gramophone Award" }, correctIndex = 0 },
            new TriviaQuestion { question = "What British band is known for 'Yellow' and 'Fix You'?", answers = new string[] { "Coldplay" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of the annual Nigerian music awards?", answers = new string[] { "Headies" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music genre blends electronic music with African rhythms?", answers = new string[] { "Afrobeats" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the most subscribed music channel on YouTube?", answers = new string[] { "T-Series" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does the term 'going platinum' mean in music?", answers = new string[] { "Selling over 1 million copies" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Auto-Tune used for in music?", answers = new string[] { "Pitch correction for vocals" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous music venue in London is known for its proms concerts?", answers = new string[] { "Royal Albert Hall" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year did Apple Music launch?", answers = new string[] { "2015" }, correctIndex = 0 },
            new TriviaQuestion { question = "What format replaced CDs as the main way to listen to music?", answers = new string[] { "Streaming" }, correctIndex = 0 },
            new TriviaQuestion { question = "What musical term means to play gradually louder?", answers = new string[] { "Crescendo" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a mixtape in modern hip hop?", answers = new string[] { "A free or unofficial collection of songs" }, correctIndex = 0 },
            new TriviaQuestion { question = "What South Korean group has members named RM, Jin, Suga, J-Hope, Jimin, V and Jungkook?", answers = new string[] { "BTS" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of the annual Ghana music awards?", answers = new string[] { "Ghana Music Awards (VGMAs)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music format made a comeback in recent years with collectors?", answers = new string[] { "Vinyl (records)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does the term 'feature' or 'feat.' mean on a song?", answers = new string[] { "A guest artist appears on the track" }, correctIndex = 0 },
            new TriviaQuestion { question = "What legendary festival took place in 1969 on a farm in New York?", answers = new string[] { "Woodstock" }, correctIndex = 0 },
            new TriviaQuestion { question = "What British singer released the album 'Divide' represented by a division symbol?", answers = new string[] { "Ed Sheeran" }, correctIndex = 0 },
            new TriviaQuestion { question = "What K-pop group is known for 'How You Like That' and 'Pink Venom'?", answers = new string[] { "BLACKPINK" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Afrobeats most associated with?", answers = new string[] { "Nigeria" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does a music A&R person do?", answers = new string[] { "Artists and Repertoire - they discover and sign new talent" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous London music market is known for vinyl and vintage records?", answers = new string[] { "Rough Trade or Camden Market" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the term for when two artists release a song together?", answers = new string[] { "Collaboration (collab)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What social media platform is most used by musicians for promotion?", answers = new string[] { "Instagram" }, correctIndex = 0 },
            new TriviaQuestion { question = "What type of concert features one artist performing multiple nights in the same venue?", answers = new string[] { "Residency" }, correctIndex = 0 },
            new TriviaQuestion { question = "What West African genre combines highlife with modern pop?", answers = new string[] { "Afrobeats" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the Billboard Hot 100?", answers = new string[] { "The main US music chart ranking songs by popularity" }, correctIndex = 0 },

            // ===== MORE ARTIST QUESTIONS =====
            new TriviaQuestion { question = "What Doja Cat song went viral with a cow-themed music video?", answers = new string[] { "Mooo!" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Doja Cat's real name?", answers = new string[] { "Amala Ratna Zandile Dlamini" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Megan Thee Stallion phrase became a viral catchphrase?", answers = new string[] { "Hot Girl Summer" }, correctIndex = 0 },
            new TriviaQuestion { question = "What university did Megan Thee Stallion graduate from?", answers = new string[] { "Texas Southern University" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Lil Nas X song broke records by topping the charts for 19 weeks?", answers = new string[] { "Old Town Road" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre did Lil Nas X blend with hip hop in Old Town Road?", answers = new string[] { "Country" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Bad Bunny song was the most streamed on Spotify in 2022?", answers = new string[] { "Me Porto Bonito" }, correctIndex = 0 },
            new TriviaQuestion { question = "What language does Bad Bunny primarily sing in?", answers = new string[] { "Spanish" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Bad Bunny from?", answers = new string[] { "Puerto Rico" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Post Malone song features the lyric 'I fall apart'?", answers = new string[] { "I Fall Apart" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre blend is Post Malone known for?", answers = new string[] { "Hip hop mixed with pop and rock" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nigerian artist is known as Davido?", answers = new string[] { "David Adedeji Adeleke" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Davido song became a wedding anthem in Africa?", answers = new string[] { "Assurance" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the biggest music festival in Ghana?", answers = new string[] { "Afrochella (now Afro Future)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ghanaian artist is known for the song 'Second Sermon'?", answers = new string[] { "Black Sherif" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Black Sherif's real name?", answers = new string[] { "Mohammed Ismail Sherif" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Stonebwoy from?", answers = new string[] { "Ghana" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre does Stonebwoy primarily make?", answers = new string[] { "Dancehall and Afrobeats" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ghanaian-British artist made the song 'Don't Rush'?", answers = new string[] { "Young T & Bugsey" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nigerian artist released the song 'Soso'?", answers = new string[] { "Omah Lay" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Rema from?", answers = new string[] { "Nigeria" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Rema song became a massive global hit featuring Selena Gomez?", answers = new string[] { "Calm Down" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Rema's real name?", answers = new string[] { "Divine Ikubor" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Asake song features the repeated lyric 'Joha'?", answers = new string[] { "Joha" }, correctIndex = 0 },
            new TriviaQuestion { question = "What record label is Asake signed to?", answers = new string[] { "YBNL" }, correctIndex = 0 },
            new TriviaQuestion { question = "What 21 Savage song features the lyric 'a lot'?", answers = new string[] { "A Lot" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country was 21 Savage revealed to actually be from?", answers = new string[] { "United Kingdom" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Lizzo's real name?", answers = new string[] { "Melissa Viviane Jefferson" }, correctIndex = 0 },
            new TriviaQuestion { question = "What instrument does Lizzo famously play on stage?", answers = new string[] { "Flute" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Lizzo song became an empowerment anthem in 2019?", answers = new string[] { "Truth Hurts" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ed Sheeran song was the most streamed on Spotify for years?", answers = new string[] { "Shape of You" }, correctIndex = 0 },
            new TriviaQuestion { question = "What instrument is Ed Sheeran known for using in live performances?", answers = new string[] { "Loop pedal and acoustic guitar" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Ed Sheeran from?", answers = new string[] { "England" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Sam Smith song was a James Bond theme?", answers = new string[] { "Writing's on the Wall (Spectre)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Harry Styles song went viral with the phrase 'watermelon sugar high'?", answers = new string[] { "Watermelon Sugar" }, correctIndex = 0 },
            new TriviaQuestion { question = "What boy band was Harry Styles a member of?", answers = new string[] { "One Direction" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Olivia Rodrigo song broke Spotify streaming records in 2021?", answers = new string[] { "drivers license" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Disney show did Olivia Rodrigo star in?", answers = new string[] { "High School Musical: The Musical: The Series" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Olivia Rodrigo's debut album?", answers = new string[] { "SOUR" }, correctIndex = 0 },
            new TriviaQuestion { question = "What duo is known for the song 'Closer' released in 2016?", answers = new string[] { "The Chainsmokers" }, correctIndex = 0 },
            new TriviaQuestion { question = "What DJ is known for the song 'Titanium' with Sia?", answers = new string[] { "David Guetta" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Sia known for wearing during performances?", answers = new string[] { "A large wig covering her face" }, correctIndex = 0 },
            new TriviaQuestion { question = "What band released 'Somebody That I Used to Know'?", answers = new string[] { "Gotye (featuring Kimbra)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What rapper is famous for 'HUMBLE' and 'DNA'?", answers = new string[] { "Kendrick Lamar" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is The Kid LAROI from?", answers = new string[] { "Australia" }, correctIndex = 0 },
            new TriviaQuestion { question = "What The Kid LAROI and Justin Bieber song was a massive hit?", answers = new string[] { "Stay" }, correctIndex = 0 },

            // ===== MUSIC HISTORY AND GENERAL =====
            new TriviaQuestion { question = "What decade is considered the golden age of hip hop?", answers = new string[] { "The 1990s" }, correctIndex = 0 },
            new TriviaQuestion { question = "What two rappers had a famous East Coast vs West Coast rivalry?", answers = new string[] { "Tupac and Biggie (Notorious B.I.G.)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Tupac's full name?", answers = new string[] { "Tupac Amaru Shakur" }, correctIndex = 0 },
            new TriviaQuestion { question = "What was Notorious B.I.G.'s real name?", answers = new string[] { "Christopher George Latore Wallace" }, correctIndex = 0 },
            new TriviaQuestion { question = "What year did Tupac pass away?", answers = new string[] { "1996" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city was Tupac shot in?", answers = new string[] { "Las Vegas" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Bob Marley song is considered a reggae anthem?", answers = new string[] { "One Love or No Woman No Cry" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country was Bob Marley from?", answers = new string[] { "Jamaica" }, correctIndex = 0 },
            new TriviaQuestion { question = "What band had members John, Paul, George and Ringo?", answers = new string[] { "The Beatles" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city are The Beatles from?", answers = new string[] { "Liverpool, England" }, correctIndex = 0 },
            new TriviaQuestion { question = "What rock band is known for 'Stairway to Heaven'?", answers = new string[] { "Led Zeppelin" }, correctIndex = 0 },
            new TriviaQuestion { question = "What rock band's lead singer is Mick Jagger?", answers = new string[] { "The Rolling Stones" }, correctIndex = 0 },
            new TriviaQuestion { question = "What 1970s band is known for 'Stayin' Alive'?", answers = new string[] { "Bee Gees" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre of music is associated with New Orleans and brass instruments?", answers = new string[] { "Jazz" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the term for singing without any musical instruments?", answers = new string[] { "A cappella" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does BPM stand for in music?", answers = new string[] { "Beats Per Minute" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the term for the speed of a song?", answers = new string[] { "Tempo" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the chorus of a song?", answers = new string[] { "The repeated main section" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a bridge in a song?", answers = new string[] { "A contrasting section that connects parts of the song" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does it mean when a song goes gold?", answers = new string[] { "It sold 500,000 copies" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does it mean when a song is certified diamond?", answers = new string[] { "It sold 10 million copies" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the verse of a song?", answers = new string[] { "The section that tells the story and changes each time" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a hook in a song?", answers = new string[] { "The catchy part that grabs the listener" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music genre is characterized by a 4/4 beat and electronic sounds?", answers = new string[] { "EDM (Electronic Dance Music)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of the annual American music awards voted by fans?", answers = new string[] { "American Music Awards (AMAs)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What TV show features singers competing with celebrity coaches?", answers = new string[] { "The Voice" }, correctIndex = 0 },
            new TriviaQuestion { question = "What TV show created by Simon Cowell discovers singers?", answers = new string[] { "American Idol or X Factor" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a remix in music?", answers = new string[] { "An altered version of an original song" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is sampling in music?", answers = new string[] { "Using a portion of another song in a new track" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a bar in rap music?", answers = new string[] { "A line or measure of lyrics" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does it mean to freestyle in rap?", answers = new string[] { "Rapping improvised lyrics without preparation" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a cypher in hip hop culture?", answers = new string[] { "A circle where rappers take turns freestyling" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous hip hop TV show features rappers in freestyle battles?", answers = new string[] { "Wild 'N Out or BET Hip Hop Awards cyphers" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the term for the main melody of a song?", answers = new string[] { "The tune or melody" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is harmony in music?", answers = new string[] { "Two or more notes played together" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a chord?", answers = new string[] { "Three or more notes played at the same time" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nigerian music producer is behind many Afrobeats hits?", answers = new string[] { "Don Jazzy" }, correctIndex = 0 },
            new TriviaQuestion { question = "What record label did Don Jazzy found?", answers = new string[] { "Mavin Records" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Afrofusion?", answers = new string[] { "A blend of Afrobeats with other genres like dancehall and pop" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nigerian genre blends percussion with Yoruba talking drums?", answers = new string[] { "Fuji music" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Ghanaian genre blends highlife with hip hop?", answers = new string[] { "Hiplife" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music genre from the Caribbean features fast rhythms and dance?", answers = new string[] { "Soca" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music genre features artists like Vybz Kartel and Sean Paul?", answers = new string[] { "Dancehall" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Sean Paul from?", answers = new string[] { "Jamaica" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous record label has signed artists like Rihanna and Jay-Z?", answers = new string[] { "Roc Nation" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous hip hop label was founded by Dr. Dre and Jimmy Iovine?", answers = new string[] { "Aftermath Entertainment" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of Kanye West's record label?", answers = new string[] { "GOOD Music" }, correctIndex = 0 },
            new TriviaQuestion { question = "What UK genre blends garage with grime and features MCs?", answers = new string[] { "Grime" }, correctIndex = 0 },
            new TriviaQuestion { question = "What UK artist is known as the Godfather of Grime?", answers = new string[] { "Wiley" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Stormzy song became a UK anthem for Black empowerment?", answers = new string[] { "Shut Up or Vossi Bop" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country is Stormzy from?", answers = new string[] { "England (London)" }, correctIndex = 0 },
            new TriviaQuestion { question = "What J Hus song features the lyric 'did you see what I done'?", answers = new string[] { "Did You See" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is grime music's typical BPM range?", answers = new string[] { "Around 140 BPM" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous venue in New York is known for iconic rap performances?", answers = new string[] { "Madison Square Garden" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does it mean when an artist 'drops' an album?", answers = new string[] { "They release it" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a deluxe edition of an album?", answers = new string[] { "A re-release with bonus tracks" }, correctIndex = 0 },
            new TriviaQuestion { question = "What streaming milestone equals one album sale?", answers = new string[] { "1,500 streams" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the most Grammy-awarded album category called?", answers = new string[] { "Album of the Year" }, correctIndex = 0 },
            new TriviaQuestion { question = "What festival takes place annually in Glastonbury England?", answers = new string[] { "Glastonbury Festival" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Nigerian festival celebrates African music and culture in December?", answers = new string[] { "Afro Nation or Afrochella" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Latin genre features reggaeton rhythms?", answers = new string[] { "Reggaeton" }, correctIndex = 0 },
            new TriviaQuestion { question = "What country did reggaeton originate from?", answers = new string[] { "Puerto Rico" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the term for when an artist releases music independently without a label?", answers = new string[] { "Independent or indie release" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a music label's main role?", answers = new string[] { "Funding, distributing, and marketing an artist's music" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Drake and Future collaborative mixtape came out in 2015?", answers = new string[] { "What a Time to Be Alive" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is Future's real name?", answers = new string[] { "Nayvadius DeMun Cash" }, correctIndex = 0 },
            new TriviaQuestion { question = "What city is Future from?", answers = new string[] { "Atlanta, Georgia" }, correctIndex = 0 },
            new TriviaQuestion { question = "What genre is Atlanta most famous for contributing to?", answers = new string[] { "Trap music" }, correctIndex = 0 },
            new TriviaQuestion { question = "What trio from Atlanta created the Migos?", answers = new string[] { "Quavo, Offset, and Takeoff" }, correctIndex = 0 },
            new TriviaQuestion { question = "What Migos song popularized the phrase 'bad and boujee'?", answers = new string[] { "Bad and Boujee" }, correctIndex = 0 },
            new TriviaQuestion { question = "What late Migos member passed away in 2022?", answers = new string[] { "Takeoff" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the name of the annual BET Awards?", answers = new string[] { "Black Entertainment Television Awards" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does the term 'GOAT' mean in music?", answers = new string[] { "Greatest of All Time" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does 'dropping bars' mean in rap?", answers = new string[] { "Delivering impressive rap lyrics" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a diss track?", answers = new string[] { "A song made to insult or criticize another artist" }, correctIndex = 0 },
            new TriviaQuestion { question = "What famous rap beef happened between Kendrick Lamar and Drake in 2024?", answers = new string[] { "The Not Like Us beef" }, correctIndex = 0 },
            new TriviaQuestion { question = "What does 'ghostwriting' mean in music?", answers = new string[] { "Writing songs for another artist without credit" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is a feature in a song?", answers = new string[] { "When a guest artist appears on another artist's track" }, correctIndex = 0 },
            new TriviaQuestion { question = "What is the difference between a single and an album?", answers = new string[] { "A single is one song, an album is a full collection" }, correctIndex = 0 },
            new TriviaQuestion { question = "What music platform is known for discovering independent artists?", answers = new string[] { "SoundCloud" }, correctIndex = 0 },
            new TriviaQuestion { question = "What subgenre of rap emerged from SoundCloud around 2016?", answers = new string[] { "SoundCloud rap" }, correctIndex = 0 },
            new TriviaQuestion { question = "What late rapper was a pioneer of SoundCloud rap known for 'SAD!'?", answers = new string[] { "XXXTentacion" }, correctIndex = 0 },
            new TriviaQuestion { question = "What late rapper was known for 'Lucid Dreams'?", answers = new string[] { "Juice WRLD" }, correctIndex = 0 },
        };
    }
}

